config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  #delete "/products/:id", to: "products#destroy"
  #patch "/products/:id", to: "products#update"
  #post "/products", to: "products#create"
  #get "/products/new", to: "products#new", as: :new_product
  #get "/products", to: "products#index"
  #get "/products/:id", to: "products#show", as: :product
  #get "/products/:id/edit", to: "products#edit", as: :edit_product
  resources :products, path: "/"  # Equivale a todas las rutas de arriba y establece como root a /
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env["HTTP_ACCEPT_LANGUAGE"]&.scan(/^[a-z]{2}/).first
  end

  # IMPORTANTE EL & -> es como if  request.env["HTTP_ACCEPT_LANGUAGE"] then  -> .scan(/^[a-z]{2}/).first
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t(".created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if categorie.update(category_params)
      redirect_to categories_url, notice: t(".updated")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private

  def category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.with_attached_photo # attached -> IMPORTANTE PARA TRAER LOS ATTACHED EN UNA SOLA CONSULTA
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: t(".created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to products_path, notice: t(".updated"), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path, notice: t(".destroyed"), status: :see_other
  end

  private

  def product_params # Metodo privado  para reutilizar codigo
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= category.name %>
  <%= link_to t('.edit'), edit_category_path(category) %>
  <%= link_to t('.delete'), category_path(category), 
  data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
   } %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>
<%= render "form", category: @category %>
<div>
  <%= link_to t('.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Categorias</h1>
<%= render partial: 'category', collection: @categories %>
<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>
<%= render "form", category: @category %>
<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursoRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>
  <br/>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
  <div>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>
  <br/>
  <%= form.submit %>
<% end %>

app/views/products/_product.html.erb
 <!-- Render One Product Model -->
<%= link_to product_path(product.id), class: 'product' do %>
  <%= image_tag product.photo, width: 150 if product.photo.attached? %>
  <h2><%= product.title %></h2>
<% end %>

app/views/products/edit.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Productos</h1>
<%= render partial: 'product', collection: @products %>

app/views/products/new.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form' %>

app/views/products/show.html.erb
<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>
<h1 class='title'><%= @product.title %></h1>
<p class='description'><%= @product.description %></p>
<span class='price'><%= @product.price %></span>
<p><%= link_to 'Editar Producto', edit_product_path(@product)%></p>
<p>
  <%= link_to 'Eliminar Producto', product_path(@product), 
  data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
   } %>
</p>

app/views/shared/_flash.html.erb
<%= notice %>
<%= alert %>

app/views/shared/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>
  <br/>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <br/>
  <%= form.submit %>
<% end %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
    <h1>Mercado Online</h1>
<% end %>


<%= link_to 'Agregar producto', new_product_path %>